name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag my-image-name:latest

    - name: Create container and extract binary
      run: |
        docker create --name temp_container my-image-name:latest
        docker cp temp_container:/usr/bin/somalier somalier-blob
        docker rm temp_container

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: somalier-blob
        path: somalier-blob
