name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-image-name:latest -f docker/Dockerfile .

      - name: Create container and extract binary
        run: |
          docker create --name temp_container my-image-name:latest
          docker cp temp_container:/usr/bin/somalier somalier-blob
          docker rm temp_container

      # Uncomment if you wish to upload the binary as an artifact
      # - name: Upload binary as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: somalier-blob
      #     path: somalier-blob

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: somalier-blob
